title: Fichier

fields:
  nicename:
    label: Nom du lien
    type: text
    placeholder: "{{model.filename}}"
    help: Utilisé à la place du nom du fichier pour les téléchargements

  caption:
    label: Légende
    type: text
